/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javase.oe.gui;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdullah
 */
public class JFrameTestComponents extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTestComponents
     */
    public JFrameTestComponents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupColors = new javax.swing.ButtonGroup();
        jPanelWelcome = new javax.swing.JPanel();
        jButtonWelcome = new javax.swing.JButton();
        jTextFieldWelcome = new javax.swing.JTextField();
        jLabelWelcome = new javax.swing.JLabel();
        jPanelColors = new javax.swing.JPanel();
        jRadioButtonBlue = new javax.swing.JRadioButton();
        jRadioButtonGreen = new javax.swing.JRadioButton();
        jRadioButtonRed = new javax.swing.JRadioButton();
        jButtonColors = new javax.swing.JButton();
        jPanelSports = new javax.swing.JPanel();
        jCheckBoxFootball = new javax.swing.JCheckBox();
        jCheckBoxBasketball = new javax.swing.JCheckBox();
        jCheckBoxVolleyball = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSports = new javax.swing.JTextArea();
        jButtonSports = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelSelectCountry = new javax.swing.JLabel();
        jComboBoxCountries = new javax.swing.JComboBox<>();
        jLabelCountryChoosen = new javax.swing.JLabel();
        jTextFieldCountryChoosen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelWelcome.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Welcome Panel"));
        jPanelWelcome.setOpaque(false);

        jButtonWelcome.setText("Say Hello");
        jButtonWelcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWelcomeActionPerformed(evt);
            }
        });

        jLabelWelcome.setText("User name");

        javax.swing.GroupLayout jPanelWelcomeLayout = new javax.swing.GroupLayout(jPanelWelcome);
        jPanelWelcome.setLayout(jPanelWelcomeLayout);
        jPanelWelcomeLayout.setHorizontalGroup(
            jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWelcomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonWelcome))
                .addGap(162, 162, 162))
        );
        jPanelWelcomeLayout.setVerticalGroup(
            jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelWelcome))
                    .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jTextFieldWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonWelcome)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanelColors.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Colors panel"));
        jPanelColors.setOpaque(false);

        buttonGroupColors.add(jRadioButtonBlue);
        jRadioButtonBlue.setText("Blue");
        jRadioButtonBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBlueActionPerformed(evt);
            }
        });

        buttonGroupColors.add(jRadioButtonGreen);
        jRadioButtonGreen.setText("Green");
        jRadioButtonGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGreenActionPerformed(evt);
            }
        });

        buttonGroupColors.add(jRadioButtonRed);
        jRadioButtonRed.setSelected(true);
        jRadioButtonRed.setText("Red");
        jRadioButtonRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRedActionPerformed(evt);
            }
        });

        jButtonColors.setText("Read Color Selected");
        jButtonColors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelColorsLayout = new javax.swing.GroupLayout(jPanelColors);
        jPanelColors.setLayout(jPanelColorsLayout);
        jPanelColorsLayout.setHorizontalGroup(
            jPanelColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColorsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonRed)
                    .addGroup(jPanelColorsLayout.createSequentialGroup()
                        .addGroup(jPanelColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButtonGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonColors)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelColorsLayout.setVerticalGroup(
            jPanelColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColorsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jRadioButtonRed)
                .addGap(18, 18, 18)
                .addGroup(jPanelColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonBlue)
                    .addComponent(jButtonColors))
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonGreen)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelSports.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sports Panel"));
        jPanelSports.setOpaque(false);

        jCheckBoxFootball.setText("Football");
        jCheckBoxFootball.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxFootballItemStateChanged(evt);
            }
        });

        jCheckBoxBasketball.setText("Basketball");
        jCheckBoxBasketball.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxBasketballItemStateChanged(evt);
            }
        });

        jCheckBoxVolleyball.setText("Volleyball");
        jCheckBoxVolleyball.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxVolleyballItemStateChanged(evt);
            }
        });

        jTextAreaSports.setColumns(20);
        jTextAreaSports.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSports);

        jButtonSports.setText("Read Sports");
        jButtonSports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSportsLayout = new javax.swing.GroupLayout(jPanelSports);
        jPanelSports.setLayout(jPanelSportsLayout);
        jPanelSportsLayout.setHorizontalGroup(
            jPanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSportsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxVolleyball, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxBasketball, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxFootball, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSportsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSportsLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButtonSports)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSportsLayout.setVerticalGroup(
            jPanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSportsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSportsLayout.createSequentialGroup()
                        .addComponent(jCheckBoxFootball)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxBasketball)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxVolleyball))
                    .addGroup(jPanelSportsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSports)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javase/oe/gui/B612_20171213_182834.jpg"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Choose Country"));
        jPanel1.setOpaque(false);

        jLabelSelectCountry.setText("Select Country");

        jComboBoxCountries.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eygpt", "Saudi", "Qater", " " }));
        jComboBoxCountries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCountriesActionPerformed(evt);
            }
        });

        jLabelCountryChoosen.setText("Country Selected");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCountryChoosen, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCountryChoosen, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSelectCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxCountries, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelectCountry)
                    .addComponent(jComboBoxCountries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCountryChoosen)
                    .addComponent(jTextFieldCountryChoosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelSports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelColors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(333, 333, 333))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelSports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonWelcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWelcomeActionPerformed
          String userName =  jTextFieldWelcome.getText();
//        System.out.println("Welcome to my project : "+userName);
        JOptionPane.showMessageDialog(null, "Welcome to my project : "+userName);
    }//GEN-LAST:event_jButtonWelcomeActionPerformed

    private void jRadioButtonRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRedActionPerformed
            this.getContentPane().setBackground(Color.RED);
    }//GEN-LAST:event_jRadioButtonRedActionPerformed

    private void jRadioButtonBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBlueActionPerformed
    this.getContentPane().setBackground(Color.BLUE);
    }//GEN-LAST:event_jRadioButtonBlueActionPerformed

    private void jRadioButtonGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGreenActionPerformed
        this.getContentPane().setBackground(Color.GREEN);
    }//GEN-LAST:event_jRadioButtonGreenActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /// set default red for background 
        this.getContentPane().setBackground(Color.RED);
        
        // set action commands for radio buttons 
        jRadioButtonRed.setActionCommand("Red");
        jRadioButtonBlue.setActionCommand("Blue");
        jRadioButtonGreen.setActionCommand("Green");
        
    }//GEN-LAST:event_formWindowOpened

    private void jButtonColorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorsActionPerformed
            /// read radio button selected using Button Group and action Command
           String radioChoosen = buttonGroupColors.getSelection().getActionCommand();
           System.out.println("Radio choosen = "+radioChoosen);
    }//GEN-LAST:event_jButtonColorsActionPerformed

    private void jCheckBoxFootballItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxFootballItemStateChanged
           printSportsSelected();
    }//GEN-LAST:event_jCheckBoxFootballItemStateChanged

    private void jCheckBoxBasketballItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxBasketballItemStateChanged
        printSportsSelected();
    }//GEN-LAST:event_jCheckBoxBasketballItemStateChanged

    private void jCheckBoxVolleyballItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxVolleyballItemStateChanged
            printSportsSelected();
    }//GEN-LAST:event_jCheckBoxVolleyballItemStateChanged

    private void jButtonSportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSportsActionPerformed
        printSportsSelected();
    }//GEN-LAST:event_jButtonSportsActionPerformed

    private void jComboBoxCountriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCountriesActionPerformed
               String choosenCountry =  jComboBoxCountries.getSelectedItem().toString();
               jTextFieldCountryChoosen.setText(choosenCountry);
    }//GEN-LAST:event_jComboBoxCountriesActionPerformed

    public void printSportsSelected(){
           String sportsSelected = 
                    "Football "+(jCheckBoxFootball.isSelected()?"Yes":"No")
                    +"\nBasketball "+(jCheckBoxBasketball.isSelected()?"Yes":"No")
                    +"\nVolleyball "+(jCheckBoxVolleyball.isSelected()?"Yes":"No");
            
//            System.out.println(sportsSelected);
            jTextAreaSports.setText(sportsSelected);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTestComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTestComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTestComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTestComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTestComponents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupColors;
    private javax.swing.JButton jButtonColors;
    private javax.swing.JButton jButtonSports;
    private javax.swing.JButton jButtonWelcome;
    private javax.swing.JCheckBox jCheckBoxBasketball;
    private javax.swing.JCheckBox jCheckBoxFootball;
    private javax.swing.JCheckBox jCheckBoxVolleyball;
    private javax.swing.JComboBox<String> jComboBoxCountries;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCountryChoosen;
    private javax.swing.JLabel jLabelSelectCountry;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelColors;
    private javax.swing.JPanel jPanelSports;
    private javax.swing.JPanel jPanelWelcome;
    private javax.swing.JRadioButton jRadioButtonBlue;
    private javax.swing.JRadioButton jRadioButtonGreen;
    private javax.swing.JRadioButton jRadioButtonRed;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSports;
    private javax.swing.JTextField jTextFieldCountryChoosen;
    private javax.swing.JTextField jTextFieldWelcome;
    // End of variables declaration//GEN-END:variables
}
