/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javase.oe.gui;

import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdullah
 */
public class JFrameMasterForm extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMasterForm
     */
    public JFrameMasterForm() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPaneMaster = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUserActions = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuProductsSetup = new javax.swing.JMenu();
        jMenuItemSoftware = new javax.swing.JMenuItem();
        jMenuItemHadrware = new javax.swing.JMenuItem();
        jMenuItemManual = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Master OE");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPaneMasterLayout = new javax.swing.GroupLayout(jDesktopPaneMaster);
        jDesktopPaneMaster.setLayout(jDesktopPaneMasterLayout);
        jDesktopPaneMasterLayout.setHorizontalGroup(
            jDesktopPaneMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        jDesktopPaneMasterLayout.setVerticalGroup(
            jDesktopPaneMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        jMenuUserActions.setText("User Actions");
        jMenuUserActions.setEnabled(false);

        jMenuItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuUserActions.add(jMenuItemLogout);

        jMenuItemExit.setText("Exit Application");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuUserActions.add(jMenuItemExit);

        jMenuBar1.add(jMenuUserActions);

        jMenuProductsSetup.setText("Products Setup");
        jMenuProductsSetup.setEnabled(false);

        jMenuItemSoftware.setText("Software");
        jMenuProductsSetup.add(jMenuItemSoftware);

        jMenuItemHadrware.setText("Hadrware");
        jMenuProductsSetup.add(jMenuItemHadrware);

        jMenuItemManual.setText("Manual");
        jMenuProductsSetup.add(jMenuItemManual);

        jMenuBar1.add(jMenuProductsSetup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMaster)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMaster)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        // Show Login internal frame
      showLoginScreen();
    }//GEN-LAST:event_formWindowOpened

    private void showLoginScreen(){
            JInternalFrameLogin loginscreen = new JInternalFrameLogin(this);
        loginscreen.setVisible(true);
        jDesktopPaneMaster.add(loginscreen);
       // loginscreen.setLocation(250, 300);
        setInternalFrameLocationCentered(loginscreen);
    }
    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        /// show login internal frame screen
         showLoginScreen();
        
        // change menu visibility to false
        changeMenuVisibility(false);
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
            int option = JOptionPane.showConfirmDialog(null, "Are You sure to exit ?", "Exit Application ...",
                            JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
                     if (option == JOptionPane.YES_OPTION){
                            System.exit(0);
                     }
    }//GEN-LAST:event_jMenuItemExitActionPerformed

  public void setInternalFrameLocationCentered(JInternalFrame jInternalFrame){
             double desktopWidth = this.jDesktopPaneMaster.getSize().getWidth();
        double desktopHeight = this.jDesktopPaneMaster.getSize().getHeight();
        double jInternalFrameWidth = jInternalFrame.getSize().getWidth();
        double jInternalFrameHeight = jInternalFrame.getSize().getHeight();

        int x = (int) ((desktopWidth - jInternalFrameWidth) / 2);
        int y = (int) ((desktopHeight - jInternalFrameHeight) / 2);
        jInternalFrame.setLocation(x, y);
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMasterForm().setVisible(true);
            }
        });
    }

    public JMenu getjMenuProductsSetup() {
        return jMenuProductsSetup;
    }

    public void setjMenuProductsSetup(JMenu jMenuProductsSetup) {
        this.jMenuProductsSetup = jMenuProductsSetup;
    }

    public JMenu getjMenuUserActions() {
        return jMenuUserActions;
    }

    public void setjMenuUserActions(JMenu jMenuUserActions) {
        this.jMenuUserActions = jMenuUserActions;
    }

    public void changeMenuVisibility(boolean valid){
            this.getjMenuUserActions().setEnabled(valid);
            this.getjMenuProductsSetup().setEnabled(valid);
    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneMaster;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemHadrware;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemManual;
    private javax.swing.JMenuItem jMenuItemSoftware;
    private javax.swing.JMenu jMenuProductsSetup;
    private javax.swing.JMenu jMenuUserActions;
    // End of variables declaration//GEN-END:variables
}
